package heartk.eda

class EDAFeatures(
    var skewnessEda: Double? = null,
    var kurtosisEda: Double? = null,
    var stdEda: Double? = null,
    var varEda: Double? = null,
    var meanEda: Double? = null,
    var minEda: Double? = null,
    var maxEda: Double? = null,
    var rangeEda: Double? = null,
    var medianEda: Double? = null,
    var minPhasicEda: Double? = null,
    var maxPhasicEda: Double? = null,
    var rangePhasicEda: Double? = null,
    var skewnessPhasicEda: Double? = null,
    var kurtosisPhasicEda: Double? = null,
    var stdPhasicEda: Double? = null,
    var varPhasicEda: Double? = null,
    var meanPhasicEda: Double? = null,
    var medianPhasicEda: Double? = null,
    var minTonicEda: Double? = null,
    var maxTonicEda: Double? = null,
    var rangeTonicEda: Double? = null,
    var skewnessTonicEda: Double? = null,
    var kurtosisTonicEda: Double? = null,
    var stdTonicEda: Double? = null,
    var varTonicEda: Double? = null,
    var meanTonicEda: Double? = null,
    var medianTonicEda: Double? = null,
    var peaksEda: Double? = null,
    var meanInstantaneousPeaksEda: Double? = null,
    var meanPeaksHeightEda: Double? = null,
    var peaksHeight95Eda: Double? = null,
    var peaksHeight85Eda: Double? = null,
    var peaksHeight75Eda: Double? = null,
    var peaksHeight65Eda: Double? = null,
    var peaksHeight50Eda: Double? = null,
    var peaksHeight25Eda: Double? = null,
    var instantaneousPeaks95Eda: Double? = null,
    var instantaneousPeaks85Eda: Double? = null,
    var instantaneousPeaks75Eda: Double? = null,
    var instantaneousPeaks65Eda: Double? = null,
    var instantaneousPeaks50Eda: Double? = null,
    var instantaneousPeaks25Eda: Double? = null
)
