/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package heartk

import heartk.ppg.PPG
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        val classUnderTest = PPG
        // (classUnderTest.(), "someLibraryMethod should return 'true'")
    }
}
